-- AlterTable
ALTER TABLE `articles` MODIFY `contentLanguage` ENUM('SIMPLIFIED_CHINESE', 'TRADITIONAL_CHINESE_HK', 'TRADITIONAL_CHINESE_CANTONESE', 'ENGLISH') NULL DEFAULT 'SIMPLIFIED_CHINESE';

-- AlterTable
ALTER TABLE `stories` MODIFY `contentLanguage` ENUM('SIMPLIFIED_CHINESE', 'TRADITIONAL_CHINESE_HK', 'TRADITIONAL_CHINESE_CANTONESE', 'ENGLISH') NULL DEFAULT 'SIMPLIFIED_CHINESE';

-- AlterTable
ALTER TABLE `users` MODIFY `preferredLanguage` ENUM('SIMPLIFIED_CHINESE', 'TRADITIONAL_CHINESE_HK', 'TRADITIONAL_CHINESE_CANTONESE', 'ENGLISH') NULL DEFAULT 'SIMPLIFIED_CHINESE';
