#!/usr/bin/env bash
# setup-agent-env.sh — write AGENT_EMAIL / AGENT_PASSWORD exports into your shell rc file.
#
# Usage:
#   setup-agent-env.sh                              # interactive
#   setup-email <email>                             # set AGENT_EMAIL only (passwords via prompt)
#   setup-agent-env.sh --shell zsh                  # target ~/.zshrc (default on macOS)
#   setup-agent-env.sh --shell bash                 # target ~/.bashrc
#   setup-agent-env.sh --shell fish                 # target ~/.config/fish/config.fish
#   setup-agent-env.sh --show                       # show current values
#   setup-agent-env.sh --unset                      # remove the block
#   setup-agent-env.sh --print-file                 # print which file would be edited
#
# The credentials are written inside a clearly-marked block (BEGIN/END markers)
# so --unset can reliably remove them later.

set -euo pipefail

SHELL_NAME="${SHELL##*/}"
case "$SHELL_NAME" in
  zsh)  RC="$HOME/.zshrc" ;;
  bash) RC="$HOME/.bashrc" ;;
  fish) RC="$HOME/.config/fish/config.fish" ;;
  *)    RC="$HOME/.zshrc" ;;
esac

BLOCK_BEGIN="# >>> cms-ng-agent-bridge >>>"
BLOCK_END="# <<< cms-ng-agent-bridge <<<"

while [ $# -gt 0 ]; do
  case "$1" in
    --shell)   SHELL_NAME="$2"; shift 2 ;;
    --show)    SHOW=1; shift ;;
    --unset)   UNSET=1; shift ;;
    --print-file) echo "$RC"; exit 0 ;;
    -h|--help) sed -n '3,18p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

# Re-resolve RC after --shell
case "$SHELL_NAME" in
  zsh)  RC="$HOME/.zshrc" ;;
  bash) RC="$HOME/.bashrc" ;;
  fish) RC="$HOME/.config/fish/config.fish" ;;
  *)    RC="$HOME/.zshrc" ;;
esac

if [ -n "${SHOW:-}" ]; then
  if [ -f "$RC" ] && grep -q "$BLOCK_BEGIN" "$RC"; then
    awk "/$BLOCK_BEGIN/{flag=1;next} /$BLOCK_END/{flag=0} flag" "$RC"
  else
    echo "(no cms-ng block in $RC)"
  fi
  exit 0
fi

if [ -n "${UNSET:-}" ]; then
  if [ -f "$RC" ] && grep -q "$BLOCK_BEGIN" "$RC"; then
    # Use sed to remove the block including its trailing newline
    sed -i.bak "/$BLOCK_BEGIN/,/$BLOCK_END/d" "$RC" && rm -f "$RC.bak"
    chmod 600 "$RC" 2>/dev/null || true
    echo "removed cms-ng block from $RC"
  else
    echo "(no cms-ng block in $RC)"
  fi
  exit 0
fi

# Write path
EMAIL="${AGENT_EMAIL:-}"
PASS="${AGENT_PASSWORD:-}"

if [ -z "$EMAIL" ]; then
  read -r -p "AGENT_EMAIL (login email): " EMAIL
fi
if [ -z "$PASS" ]; then
  read -r -s -p "AGENT_PASSWORD (login password): " PASS
  echo >&2
fi

if [ -z "$EMAIL" ] || [ -z "$PASS" ]; then
  echo "email and password are required" >&2
  exit 2
fi

# Validate the credentials actually work before persisting them
export AGENT_EMAIL="$EMAIL"
export AGENT_PASSWORD="$PASS"
TOKEN=$(bash "$(cd "$(dirname "$0")" && pwd)/get-token.sh" 2>/dev/null) || {
  echo "credential validation failed — not writing to $RC" >&2
  exit 1
}
if [ -z "$TOKEN" ]; then
  echo "credential validation produced empty token — not writing to $RC" >&2
  exit 1
fi
echo "  ✓ login verified" >&2

# Remove any prior block
if [ -f "$RC" ] && grep -q "$BLOCK_BEGIN" "$RC"; then
  sed -i.bak "/$BLOCK_BEGIN/,/$BLOCK_END/d" "$RC" && rm -f "$RC.bak"
fi

# Append new block (single-quoted to keep backslashes safe; password is base64-quoted below)
{
  echo "$BLOCK_BEGIN"
  echo "# Generated by scripts/agent/setup-agent-env.sh on $(date '+%Y-%m-%d %H:%M:%S')"
  echo "# To remove: bash scripts/agent/setup-agent-env.sh --unset"
  if [ "$SHELL_NAME" = "fish" ]; then
    echo "set -gx AGENT_EMAIL \"$EMAIL\""
    echo "set -gx AGENT_PASSWORD \"$PASS\""
  else
    # Use single quotes to avoid shell expansion inside password
    echo "export AGENT_EMAIL='$EMAIL'"
    echo "export AGENT_PASSWORD='$PASS'"
  fi
  echo "$BLOCK_END"
} >> "$RC"

chmod 600 "$RC" 2>/dev/null || true
echo
echo "wrote to: $RC (mode 600)"
echo "reload with:  source $RC"
echo "verify with:  bash scripts/agent/get-token.sh --print-env | head -1"
